# -*- coding: utf-8 -*-
"""Day02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mVUTUY983zS5MB2PN0Ejhkz1dSAjOBZL
"""

#import pandas -> working with data sets
import pandas as pd

#create the dictionary
data = {
    'Name' : ['Alice' , 'Bob' , 'Charlie' , 'David'] ,
    'Age' : [24 , 27 , 22 , 32] ,
    'City' : ['Newyoke' , 'Los Angeles' , 'Chigago' , 'Kandy']
}

print(data)

#using Pandas to convert that dictionary into a DataFrame.
df = pd.DataFrame(data)
print(df)

#Select the column and print
print("Ages in the Data Frame : ")
print(df['Age'])

#Select the column Name and print
print(df['Name'])

#Filter rows where Age is greater than 25
filtered_df = df[df['Age']>25]
print("Filtered Data Frame (Age>25) : ")
print(filtered_df)

#Add a new column
df['Salary'] = [70000 , 80000 , 60000 , 90000]
print("Data Frame After Adding Salary Column : ")
print(df)

from numpy import average
#Average of the Age
average_Age = df['Age'].mean()
print("Average Age : " , average_Age)

#print 2 rows
df.head(2)

#print last two rows
df.tail(2)

#Read the csv file into a DataFrame
df = pd.read_csv('/content/Customers.csv')

#Display the Data Frame
print(df)

#Cleaning the Data : Remove rows with missing values
#Dropna() is used to remove rows or columns that contain missing values
df_cleaned = df.dropna()
print(df_cleaned)

#Calculate the Average Salary
Average_Salary = df_cleaned['Annual_Income_(k$)'].mean()
print("Average Annual Income : " , Average_Salary)

