# -*- coding: utf-8 -*-
"""Day01NumPy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yX4TXczv9D--TJrxMXtcXXSkqhG8ZNMB
"""

#import library Numpy -> Numerical
import numpy as np

#Create a numpy array
arr = np.array([1,2,3,4,5])

#display the array
print("Array :- ")
print(arr)

#Add 10 to each element
arr_plus_10 = arr + 10
print(arr_plus_10)

#Add 5 to each element
arr_plus_5 = arr + 5
print (arr_plus_5)

#Calculare the mean of the array
mean_value = np.mean(arr)

print(f"\nMean of the arry : {mean_value : 2f}")

#Reshape the array to 2D array (5 rows, 1 column)
reshaped_arr = arr.reshape(5,1)
print("Reshaped Array :-")
print(reshaped_arr)

#2D Array/Matrix Creation
matrix_a = ([
    [1,2,3] ,
    [3,4,5] ,
    [6,7,8]
])

print(matrix_a)

matrix_d = np.array([
    [1,2,3],
    [3,4,5],
    [6,7,8]
])
print(matrix_d)

matrix_d_trans = matrix_d.T

print(matrix_d_trans)

print(matrix_d)

matrix_b = np.array([
    [9,10,11] ,
    [8,7,6],
    [6,5,4]
])

print(matrix_b)

#matrix maltipication (Dot Product)

matrix_product = np.dot(matrix_d,matrix_b)
print(matrix_product)

#set random seed for reproductibility - setting a seed is the way to make rondom number generation predictable
np.random.seed(40)

#Generate an arry of 10 random floating point numbers between 0 and 1
random_array = np.random.rand(10)
print(random_array )

#Calculate the mean of the random array
mean_value = np.mean(random_array)
print(mean_value)

#Calculate the median of the random array
median_value = np.median(random_array)
print(median_value)

#Calculate the Standard Deviation
sta_div = np.std(random_array)
print(sta_div )

#Calculate the min values
min_value = np.min(random_array)
print(min_value)

#Calculate the max values
max_value = np.max(random_array)
print(max_value)

#Reshape the random array (5,2)
reshapred_array_random = random_array.reshape(5,2)
print(random_array)
print("Reshaped Array:- ")
print(reshapred_array_random)

